version: '3.7'
services:
    api2:
        build:
            context: ./api
            dockerfile: Dockerfile
        container_name: be_api2
        ports:
            - 9002:9002
        volumes:
            - "./api:/app"
        networks:
            - webnet
        restart: always
networks:
   webnet:
